### ISSUE TITLE
DOI with trailing or leading spaces cause InvalidModel exception to be thrown

### ISSUE THREAD

**Issue by emetsger** [OA-PASS/nihms-submission#103]
If a user enters in a DOI that begins or ends with trailing spaces in step 1. of the submission workflow, the `DepositSubmission` model fails to build.

The builder should probably `trim()` the DOI string before attempting to create a `URI`.

```
java.lang.RuntimeException: Data file '10.1021/acsmedchemlett.7b00397 ' contained an invalid URI.
	at org.dataconservancy.pass.deposit.messaging.service.SubmissionProcessor.lambda$accept$38(SubmissionProcessor.java:137)
	at org.dataconservancy.pass.deposit.messaging.support.CriticalPath.performCritical(CriticalPath.java:151)
	at org.dataconservancy.pass.deposit.messaging.support.CriticalPath.performCritical(CriticalPath.java:86)
	at org.dataconservancy.pass.deposit.messaging.service.SubmissionProcessor.accept(SubmissionProcessor.java:116)
	at org.dataconservancy.pass.deposit.messaging.service.JmsSubmissionProcessor.processInternal(JmsSubmissionProcessor.java:133)
	at org.dataconservancy.pass.deposit.messaging.service.JmsSubmissionProcessor.processMessage(JmsSubmissionProcessor.java:110)
	at sun.reflect.GeneratedMethodAccessor35.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:181)
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:114)
	at org.springframework.jms.listener.adapter.MessagingMessageListenerAdapter.invokeHandler(MessagingMessageListenerAdapter.java:114)
	at org.springframework.jms.listener.adapter.MessagingMessageListenerAdapter.onMessage(MessagingMessageListenerAdapter.java:77)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:736)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:696)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:674)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:318)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:257)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1189)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1179)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1076)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.dataconservancy.nihms.builder.InvalidModel: Data file '10.1021/acsmedchemlett.7b00397 ' contained an invalid URI.
	at org.dataconservancy.nihms.builder.fs.ModelBuilder.createDepositSubmission(ModelBuilder.java:258)
	at org.dataconservancy.nihms.builder.fs.FcrepoModelBuilder.build(FcrepoModelBuilder.java:50)
	at org.dataconservancy.pass.deposit.messaging.service.SubmissionProcessor.lambda$accept$38(SubmissionProcessor.java:135)
	... 21 common frames omitted
Caused by: java.net.URISyntaxException: Illegal character in path at index 30: 10.1021/acsmedchemlett.7b00397 
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parseHierarchical(URI.java:3105)
	at java.net.URI$Parser.parse(URI.java:3063)
	at java.net.URI.<init>(URI.java:588)
	at org.dataconservancy.nihms.builder.fs.ModelBuilder.createDepositSubmission(ModelBuilder.java:255)
	... 23 common frames omitted
```

**Comment by emetsger** [comment]
In addition, the error message `Data file '10.1021/acsmedchemlett.7b00397 ' contained an invalid URI` is a bit confusing, because the first thing my mind jumps to when reading the message is that there's a `File` in the `DepositSubmission` named `10.1021/acsmedchemlett.7b00397`.
