### ISSUE TITLE
Failed submission when DOI field is left blank

### ISSUE THREAD

**Issue by jrmartino** [OA-PASS/nihms-submission#113]
ModelBuilder appears to throw an NPE getting the DOI for the submission.

Stack trace:

18:53:15.780 [eListenerContainer-2] WARN  [ SubmissionProcessor] - Unable to update status of http://fcrepo:8080/fcrepo/rest/submissions/55/62/1c/ca/55621cca-25f7-4a60-821b-71c538582a18 to 'in-progress': null
18:53:15.783 [eListenerContainer-2] ERROR [DepositServiceErrorH] - Unrecoverable error, marking http://fcrepo:8080/fcrepo/rest/submissions/55/62/1c/ca/55621cca-25f7-4a60-821b-71c538582a18 as FAILED
org.dataconservancy.pass.deposit.messaging.DepositServiceRuntimeException: Unable to update status of http://fcrepo:8080/fcrepo/rest/submissions/55/62/1c/ca/55621cca-25f7-4a60-821b-71c538582a18 to 'in-progress': null
	at org.dataconservancy.pass.deposit.messaging.service.SubmissionProcessor.accept(SubmissionProcessor.java:174)
	at org.dataconservancy.pass.deposit.messaging.service.JmsSubmissionProcessor.processInternal(JmsSubmissionProcessor.java:130)
	at org.dataconservancy.pass.deposit.messaging.service.JmsSubmissionProcessor.processMessage(JmsSubmissionProcessor.java:107)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:181)
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:114)
	at org.springframework.jms.listener.adapter.MessagingMessageListenerAdapter.invokeHandler(MessagingMessageListenerAdapter.java:114)
	at org.springframework.jms.listener.adapter.MessagingMessageListenerAdapter.onMessage(MessagingMessageListenerAdapter.java:77)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:736)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:696)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:674)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:318)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:257)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1189)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1179)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1076)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: null
	at java.net.URI$Parser.parse(URI.java:3042)
	at java.net.URI.<init>(URI.java:588)
	at org.dataconservancy.nihms.builder.fs.ModelBuilder.createDepositSubmission(ModelBuilder.java:256)
	at org.dataconservancy.nihms.builder.fs.FcrepoModelBuilder.build(FcrepoModelBuilder.java:50)
	at org.dataconservancy.pass.deposit.messaging.service.SubmissionProcessor.lambda$accept$50(SubmissionProcessor.java:155)
	at org.dataconservancy.pass.deposit.messaging.support.CriticalPath.performCritical(CriticalPath.java:155)
	at org.dataconservancy.pass.deposit.messaging.service.SubmissionProcessor.accept(SubmissionProcessor.java:116)
	... 19 common frames omitted
18:53:16.057 [eListenerContainer-4] WARN  [ SubmissionProcessor] - Unable to update status of http://fcrepo:8080/fcrepo/rest/submissions/55/62/1c/ca/55621cca-25f7-4a60-821b-71c538582a18 to 'in-progress': null
18:53:16.058 [eListenerContainer-4] ERROR [DepositServiceErrorH] - Unrecoverable error, marking http://fcrepo:8080/fcrepo/rest/submissions/55/62/1c/ca/55621cca-25f7-4a60-821b-71c538582a18 as FAILED
org.dataconservancy.pass.deposit.messaging.DepositServiceRuntimeException: Unable to update status of http://fcrepo:8080/fcrepo/rest/submissions/55/62/1c/ca/55621cca-25f7-4a60-821b-71c538582a18 to 'in-progress': null
	at org.dataconservancy.pass.deposit.messaging.service.SubmissionProcessor.accept(SubmissionProcessor.java:174)
	at org.dataconservancy.pass.deposit.messaging.service.JmsSubmissionProcessor.processInternal(JmsSubmissionProcessor.java:130)
	at org.dataconservancy.pass.deposit.messaging.service.JmsSubmissionProcessor.processMessage(JmsSubmissionProcessor.java:107)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:181)
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:114)
	at org.springframework.jms.listener.adapter.MessagingMessageListenerAdapter.invokeHandler(MessagingMessageListenerAdapter.java:114)
	at org.springframework.jms.listener.adapter.MessagingMessageListenerAdapter.onMessage(MessagingMessageListenerAdapter.java:77)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:736)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:696)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:674)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:318)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:257)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1189)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1179)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1076)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: null
	at java.net.URI$Parser.parse(URI.java:3042)
	at java.net.URI.<init>(URI.java:588)
	at org.dataconservancy.nihms.builder.fs.ModelBuilder.createDepositSubmission(ModelBuilder.java:256)
	at org.dataconservancy.nihms.builder.fs.FcrepoModelBuilder.build(FcrepoModelBuilder.java:50)
	at org.dataconservancy.pass.deposit.messaging.service.SubmissionProcessor.lambda$accept$50(SubmissionProcessor.java:155)
	at org.dataconservancy.pass.deposit.messaging.support.CriticalPath.performCritical(CriticalPath.java:155)
	at org.dataconservancy.pass.deposit.messaging.service.SubmissionProcessor.accept(SubmissionProcessor.java:116)
	... 19 common frames omitted
18:53:16.285 [eListenerContainer-3] WARN  [ SubmissionProcessor] - Unable to update status of http://fcrepo:8080/fcrepo/rest/submissions/55/62/1c/ca/55621cca-25f7-4a60-821b-71c538582a18 to 'in-progress': null
18:53:16.286 [eListenerContainer-3] ERROR [DepositServiceErrorH] - Unrecoverable error, marking http://fcrepo:8080/fcrepo/rest/submissions/55/62/1c/ca/55621cca-25f7-4a60-821b-71c538582a18 as FAILED
org.dataconservancy.pass.deposit.messaging.DepositServiceRuntimeException: Unable to update status of http://fcrepo:8080/fcrepo/rest/submissions/55/62/1c/ca/55621cca-25f7-4a60-821b-71c538582a18 to 'in-progress': null
	at org.dataconservancy.pass.deposit.messaging.service.SubmissionProcessor.accept(SubmissionProcessor.java:174)
	at org.dataconservancy.pass.deposit.messaging.service.JmsSubmissionProcessor.processInternal(JmsSubmissionProcessor.java:130)
	at org.dataconservancy.pass.deposit.messaging.service.JmsSubmissionProcessor.processMessage(JmsSubmissionProcessor.java:107)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:181)
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:114)
	at org.springframework.jms.listener.adapter.MessagingMessageListenerAdapter.invokeHandler(MessagingMessageListenerAdapter.java:114)
	at org.springframework.jms.listener.adapter.MessagingMessageListenerAdapter.onMessage(MessagingMessageListenerAdapter.java:77)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:736)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:696)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:674)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:318)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:257)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1189)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1179)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1076)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: null
	at java.net.URI$Parser.parse(URI.java:3042)
	at java.net.URI.<init>(URI.java:588)
	at org.dataconservancy.nihms.builder.fs.ModelBuilder.createDepositSubmission(ModelBuilder.java:256)
	at org.dataconservancy.nihms.builder.fs.FcrepoModelBuilder.build(FcrepoModelBuilder.java:50)
	at org.dataconservancy.pass.deposit.messaging.service.SubmissionProcessor.lambda$accept$50(SubmissionProcessor.java:155)
	at org.dataconservancy.pass.deposit.messaging.support.CriticalPath.performCritical(CriticalPath.java:155)
	at org.dataconservancy.pass.deposit.messaging.service.SubmissionProcessor.accept(SubmissionProcessor.java:116)
	... 19 common frames omitted
18:53:16.429 [eListenerContainer-4] INFO  [         DepositUtil] - Marking http://fcrepo:8080/fcrepo/rest/submissions/55/62/1c/ca/55621cca-25f7-4a60-821b-71c538582a18 as FAILED.
18:53:16.585 [eListenerContainer-2] INFO  [         DepositUtil] - Marking http://fcrepo:8080/fcrepo/rest/submissions/55/62/1c/ca/55621cca-25f7-4a60-821b-71c538582a18 as FAILED.
18:53:16.728 [eListenerContainer-3] INFO  [         DepositUtil] - Marking http://fcrepo:8080/fcrepo/rest/submissions/55/62/1c/ca/55621cca-25f7-4a60-821b-71c538582a18 as FAILED.

**Comment by Trumbore** [comment]
Fixing this should be tied in to a fix for #103, which would require cleaning up white space around a DOI.

**Comment by emetsger** [comment]
@Trumbore agreed- I'll take these two on!

**Comment by emetsger** [comment]
Fixed in 0e28750
