### ISSUE TITLE
ClassCastException when depositing a package with a filename containing spaces.

### ISSUE THREAD

**Issue by emetsger** [OA-PASS/nihms-submission#126]
^[[32m/ecs/pass-demo^[[0m ^[[36mdemo/depositservice/403d9d9b-215a-42af-b251-21dd38d20192^[[0m java.lang.ClassCastException: org.apache.abdera.parser.stax.FOMExtensibleElement cannot be cast to org.apache.abdera.model.Feed
^[[32m/ecs/pass-demo^[[0m ^[[36mdemo/depositservice/403d9d9b-215a-42af-b251-21dd38d20192^[[0m   at org.dataconservancy.pass.deposit.messaging.support.swordv2.AtomUtil.parseAtomStatement(AtomUtil.java:47)
^[[32m/ecs/pass-demo^[[0m ^[[36mdemo/depositservice/403d9d9b-215a-42af-b251-21dd38d20192^[[0m   at org.dataconservancy.pass.deposit.messaging.support.swordv2.AtomFeedStatusParser.parse(AtomFeedStatusParser.java:122)
^[[32m/ecs/pass-demo^[[0m ^[[36mdemo/depositservice/403d9d9b-215a-42af-b251-21dd38d20192^[[0m   at org.dataconservancy.pass.deposit.messaging.support.swordv2.AtomFeedStatusParser.parse(AtomFeedStatusParser.java:53)
^[[32m/ecs/pass-demo^[[0m ^[[36mdemo/depositservice/403d9d9b-215a-42af-b251-21dd38d20192^[[0m   at org.dataconservancy.pass.deposit.messaging.status.AbderaDepositStatusRefProcessor.process(AbderaDepositStatusRefProcessor.java:57)
^[[32m/ecs/pass-demo^[[0m ^[[36mdemo/depositservice/403d9d9b-215a-42af-b251-21dd38d20192^[[0m   at org.dataconservancy.pass.deposit.messaging.service.DepositTaskHelper.lambda$processDepositStatus$31(DepositTaskHelper.java:274)
^[[32m/ecs/pass-demo^[[0m ^[[36mdemo/depositservice/403d9d9b-215a-42af-b251-21dd38d20192^[[0m   at org.dataconservancy.pass.deposit.messaging.support.CriticalPath.performCritical(CriticalPath.java:156)
^[[32m/ecs/pass-demo^[[0m ^[[36mdemo/depositservice/403d9d9b-215a-42af-b251-21dd38d20192^[[0m   at org.dataconservancy.pass.deposit.messaging.service.DepositTaskHelper.processDepositStatus(DepositTaskHelper.java:165)
^[[32m/ecs/pass-demo^[[0m ^[[36mdemo/depositservice/403d9d9b-215a-42af-b251-21dd38d20192^[[0m   at org.dataconservancy.pass.deposit.messaging.service.DepositTask.run(DepositTask.java:225)
^[[32m/ecs/pass-demo^[[0m ^[[36mdemo/depositservice/403d9d9b-215a-42af-b251-21dd38d20192^[[0m   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
^[[32m/ecs/pass-demo^[[0m ^[[36mdemo/depositservice/403d9d9b-215a-42af-b251-21dd38d20192^[[0m   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
^[[32m/ecs/pass-demo^[[0m ^[[36mdemo/depositservice/403d9d9b-215a-42af-b251-21dd38d20192^[[0m   at java.lang.Thread.run(Thread.java:748)
^[[32m/ecs/pass-demo^[[0m ^[[36mdemo/depositservice/403d9d9b-215a-42af-b251-21dd38d20192^[[0m 01:02:19.794 [    Deposit-Worker-9] ERROR [DepositServiceErrorH] - Unrecoverable error, marking http://localhost:8080/fcrepo/rest/deposits/8f/a9/93/2a/8fa9932a-4d6f-4dd8-80d8-7439779f3175 as FAILED
^[[32m/ecs/pass-demo^[[0m ^[[36mdemo/depositservice/403d9d9b-215a-42af-b251-21dd38d20192^[[0m org.dataconservancy.pass.deposit.messaging.DepositServiceRuntimeException: Failed to update deposit status for [http://localhost:8080/fcrepo/rest/deposits/8f/a9/93/2a/8fa9932a-4d6f-4dd8-80d8-7439779f3175], parsing the status document referenced by http://localhost:8181/swordv2/statement/167beb07-1cbc-4547-85ff-3954109f7332.atom failed: org.apache.abdera.parser.stax.FOMExtensibleElement cannot be cast to org.apache.abdera.model.Feed
^[[32m/ecs/pass-demo^[[0m ^[[36mdemo/depositservice/403d9d9b-215a-42af-b251-21dd38d20192^[[0m   at org.dataconservancy.pass.deposit.messaging.service.DepositTaskHelper.lambda$processDepositStatus$31(DepositTaskHelper.java:280)
^[[32m/ecs/pass-demo^[[0m ^[[36mdemo/depositservice/403d9d9b-215a-42af-b251-21dd38d20192^[[0m   at org.dataconservancy.pass.deposit.messaging.support.CriticalPath.performCritical(CriticalPath.java:156)
^[[32m/ecs/pass-demo^[[0m ^[[36mdemo/depositservice/403d9d9b-215a-42af-b251-21dd38d20192^[[0m   at org.dataconservancy.pass.deposit.messaging.service.DepositTaskHelper.processDepositStatus(DepositTaskHelper.java:165)
^[[32m/ecs/pass-demo^[[0m ^[[36mdemo/depositservice/403d9d9b-215a-42af-b251-21dd38d20192^[[0m   at org.dataconservancy.pass.deposit.messaging.service.DepositTask.run(DepositTask.java:225)
^[[32m/ecs/pass-demo^[[0m ^[[36mdemo/depositservice/403d9d9b-215a-42af-b251-21dd38d20192^[[0m   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
^[[32m/ecs/pass-demo^[[0m ^[[36mdemo/depositservice/403d9d9b-215a-42af-b251-21dd38d20192^[[0m   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
^[[32m/ecs/pass-demo^[[0m ^[[36mdemo/depositservice/403d9d9b-215a-42af-b251-21dd38d20192^[[0m   at java.lang.Thread.run(Thread.java:748)
^[[32m/ecs/pass-demo^[[0m ^[[36mdemo/depositservice/403d9d9b-215a-42af-b251-21dd38d20192^[[0m Caused by: java.lang.ClassCastException: org.apache.abdera.parser.stax.FOMExtensibleElement cannot be cast to org.apache.abdera.model.Feed
^[[32m/ecs/pass-demo^[[0m ^[[36mdemo/depositservice/403d9d9b-215a-42af-b251-21dd38d20192^[[0m   at org.dataconservancy.pass.deposit.messaging.support.swordv2.AtomUtil.parseAtomStatement(AtomUtil.java:47)
^[[32m/ecs/pass-demo^[[0m ^[[36mdemo/depositservice/403d9d9b-215a-42af-b251-21dd38d20192^[[0m   at org.dataconservancy.pass.deposit.messaging.support.swordv2.AtomFeedStatusParser.parse(AtomFeedStatusParser.java:122)
^[[32m/ecs/pass-demo^[[0m ^[[36mdemo/depositservice/403d9d9b-215a-42af-b251-21dd38d20192^[[0m   at org.dataconservancy.pass.deposit.messaging.support.swordv2.AtomFeedStatusParser.parse(AtomFeedStatusParser.java:53)
^[[32m/ecs/pass-demo^[[0m ^[[36mdemo/depositservice/403d9d9b-215a-42af-b251-21dd38d20192^[[0m   at org.dataconservancy.pass.deposit.messaging.status.AbderaDepositStatusRefProcessor.process(AbderaDepositStatusRefProcessor.java:57)
^[[32m/ecs/pass-demo^[[0m ^[[36mdemo/depositservice/403d9d9b-215a-42af-b251-21dd38d20192^[[0m   at org.dataconservancy.pass.deposit.messaging.service.DepositTaskHelper.lambda$processDepositStatus$31(DepositTaskHelper.java:274)
^[[32m/ecs/pass-demo^[[0m ^[[36mdemo/depositservice/403d9d9b-215a-42af-b251-21dd38d20192^[[0m   ... 6 common frames omitted

**Comment by emetsger** [comment]
/ecs/pass-demo demo/dspace/403d9d9b-215a-42af-b251-21dd38d20192 org.apache.abdera.i18n.text.InvalidCharacterException: Invalid Character 0x20( )
/ecs/pass-demo demo/dspace/403d9d9b-215a-42af-b251-21dd38d20192   at org.apache.abdera.i18n.text.CodepointIterator$RestrictedCodepointIterator.next(CodepointIterator.java:476)
/ecs/pass-demo demo/dspace/403d9d9b-215a-42af-b251-21dd38d20192   at org.apache.abdera.i18n.text.CharUtils.verify(CharUtils.java:840)
/ecs/pass-demo demo/dspace/403d9d9b-215a-42af-b251-21dd38d20192   at org.apache.abdera.i18n.text.CharUtils.verify(CharUtils.java:858)
/ecs/pass-demo demo/dspace/403d9d9b-215a-42af-b251-21dd38d20192   at org.apache.abdera.i18n.iri.IRI.parse(IRI.java:573)
/ecs/pass-demo demo/dspace/403d9d9b-215a-42af-b251-21dd38d20192   at org.apache.abdera.i18n.iri.IRI.<init>(IRI.java:64)
/ecs/pass-demo demo/dspace/403d9d9b-215a-42af-b251-21dd38d20192   at org.swordapp.server.AtomStatement.writeTo(AtomStatement.java:66)
/ecs/pass-demo demo/dspace/403d9d9b-215a-42af-b251-21dd38d20192   at org.swordapp.server.StatementAPI.get(StatementAPI.java:75)
/ecs/pass-demo demo/dspace/403d9d9b-215a-42af-b251-21dd38d20192   at org.swordapp.server.servlets.StatementServletDefault.doGet(StatementServletDefault.java:33)
/ecs/pass-demo demo/dspace/403d9d9b-215a-42af-b251-21dd38d20192   at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
/ecs/pass-demo demo/dspace/403d9d9b-215a-42af-b251-21dd38d20192   at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
/ecs/pass-demo demo/dspace/403d9d9b-215a-42af-b251-21dd38d20192   at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:833)
/ecs/pass-demo demo/dspace/403d9d9b-215a-42af-b251-21dd38d20192   at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650)
/ecs/pass-demo demo/dspace/403d9d9b-215a-42af-b251-21dd38d20192   at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:206)
/ecs/pass-demo demo/dspace/403d9d9b-215a-42af-b251-21dd38d20192   at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
/ecs/pass-demo demo/dspace/403d9d9b-215a-42af-b251-21dd38d20192   at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
/ecs/pass-demo demo/dspace/403d9d9b-215a-42af-b251-21dd38d20192   at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
/ecs/pass-demo demo/dspace/403d9d9b-215a-42af-b251-21dd38d20192   at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
/ecs/pass-demo demo/dspace/403d9d9b-215a-42af-b251-21dd38d20192   at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
/ecs/pass-demo demo/dspace/403d9d9b-215a-42af-b251-21dd38d20192   at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
/ecs/pass-demo demo/dspace/403d9d9b-215a-42af-b251-21dd38d20192   at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
/ecs/pass-demo demo/dspace/403d9d9b-215a-42af-b251-21dd38d20192   at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
/ecs/pass-demo demo/dspace/403d9d9b-215a-42af-b251-21dd38d20192   at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
/ecs/pass-demo demo/dspace/403d9d9b-215a-42af-b251-21dd38d20192   at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
/ecs/pass-demo demo/dspace/403d9d9b-215a-42af-b251-21dd38d20192   at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
/ecs/pass-demo demo/dspace/403d9d9b-215a-42af-b251-21dd38d20192   at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
/ecs/pass-demo demo/dspace/403d9d9b-215a-42af-b251-21dd38d20192   at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
/ecs/pass-demo demo/dspace/403d9d9b-215a-42af-b251-21dd38d20192   at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
/ecs/pass-demo demo/dspace/403d9d9b-215a-42af-b251-21dd38d20192   at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
/ecs/pass-demo demo/dspace/403d9d9b-215a-42af-b251-21dd38d20192   at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:219)
/ecs/pass-demo demo/dspace/403d9d9b-215a-42af-b251-21dd38d20192   at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
/ecs/pass-demo demo/dspace/403d9d9b-215a-42af-b251-21dd38d20192   at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
/ecs/pass-demo demo/dspace/403d9d9b-215a-42af-b251-21dd38d20192   at org.eclipse.jetty.server.Server.handle(Server.java:561)
/ecs/pass-demo demo/dspace/403d9d9b-215a-42af-b251-21dd38d20192   at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:334)
/ecs/pass-demo demo/dspace/403d9d9b-215a-42af-b251-21dd38d20192   at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
/ecs/pass-demo demo/dspace/403d9d9b-215a-42af-b251-21dd38d20192   at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
/ecs/pass-demo demo/dspace/403d9d9b-215a-42af-b251-21dd38d20192   at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:104)
/ecs/pass-demo demo/dspace/403d9d9b-215a-42af-b251-21dd38d20192   at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
/ecs/pass-demo demo/dspace/403d9d9b-215a-42af-b251-21dd38d20192   at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
/ecs/pass-demo demo/dspace/403d9d9b-215a-42af-b251-21dd38d20192   at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
/ecs/pass-demo demo/dspace/403d9d9b-215a-42af-b251-21dd38d20192   at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
/ecs/pass-demo demo/dspace/403d9d9b-215a-42af-b251-21dd38d20192   at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:243)
/ecs/pass-demo demo/dspace/403d9d9b-215a-42af-b251-21dd38d20192   at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:679)
/ecs/pass-demo demo/dspace/403d9d9b-215a-42af-b251-21dd38d20192   at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:597)
/ecs/pass-demo demo/dspace/403d9d9b-215a-42af-b251-21dd38d20192   at java.lang.Thread.run(Thread.java:748)

**Comment by emetsger** [comment]
esm:~/workspaces/pass/nihms-submission (sample-package-consolidation)*$ curl -ux:y http://18.206.159.209:8181/swordv2/statement/167beb07-1cbc-4547-85ff-3954109f7332.atom
<?xml version="1.0" encoding="ISO-8859-1"?>
<sword:error href="http://www.dspace.org/ns/sword/2.0/errors/BadUrl" xmlns:sword="http://purl.org/net/sword/terms/"><atom:title xmlns:atom="http://www.w3.org/2005/Atom">ERROR</atom:title><atom:updated xmlns:atom="http://www.w3.org/2005/Atom">2018-06-30T01:30:00Z</atom:updated><atom:generator uri="http://www.dspace.org/ns/sword/2.0/" version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">dspace-help@myu.edu</atom:generator><sword:treatment>Processing failed</sword:treatment><atom:summary xmlns:atom="http://www.w3.org/2005/Atom">The item URL is invalid</atom:summary><sword:verboseDescription>org.swordapp.server.SwordError: The item URL is invalid
	at org.dspace.sword2.SwordUrlManager.getItem(SwordUrlManager.java:145)
	at org.dspace.sword2.StatementManagerDSpace.getStatement(StatementManagerDSpace.java:73)
	at org.swordapp.server.StatementAPI.get(StatementAPI.java:61)
	at org.swordapp.server.servlets.StatementServletDefault.doGet(StatementServletDefault.java:33)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:833)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:206)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:219)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:561)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:334)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:104)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:243)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:679)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:597)
	at java.lang.Thread.run(Thread.java:748)
</sword:verboseDescription><atom:link rel="alternate" type="text/html" href="http://localhost:8181/contact" xmlns:atom="http://www.w3.org/2005/Atom"/></sword:error>
esm:~/workspaces/pass/nihms-submission (sample-package-consolidation)*$

**Comment by emetsger** [comment]
Fixed with release 0.0.7-2.2 of Deposit Services.
