### ISSUE TITLE
Builder failure when mapping Policy

### ISSUE THREAD

**Issue by emetsger** [OA-PASS/nihms-submission#56]
I encounter the exception below when attempting to process this `Submission`:
```
esm:~/workspaces/pass/nihms-submission/deposit-messaging (messaging)*$ curl -u admin:moo -H "Prefer: return=representation; include=\"http://fedora.info/definitions/v4/repository#InboundReferences\"" 'http://192.168.99.100:8080/fcrepo/rest/submissions/37/83/72/4e/3783724e-1abe-4f4f-953b-cecb17a35daa'
@prefix premis:  <http://www.loc.gov/premis/rdf/v1#> .
@prefix test:  <info:fedora/test/> .
@prefix pass:  <http://example.org/pass/> .
@prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#> .
@prefix webac:  <http://fedora.info/definitions/v4/webac#> .
@prefix acl:  <http://www.w3.org/ns/auth/acl#> .
@prefix xsi:  <http://www.w3.org/2001/XMLSchema-instance> .
@prefix xmlns:  <http://www.w3.org/2000/xmlns/> .
@prefix rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix fedora:  <http://fedora.info/definitions/v4/repository#> .
@prefix xml:  <http://www.w3.org/XML/1998/namespace> .
@prefix dcjsonld:  <http://dataconservancy.org/ns/jsonld#> .
@prefix ebucore:  <http://www.ebu.ch/metadata/ontologies/ebucore/ebucore#> .
@prefix ldp:  <http://www.w3.org/ns/ldp#> .
@prefix xs:  <http://www.w3.org/2001/XMLSchema> .
@prefix fedoraconfig:  <http://fedora.info/definitions/v4/config#> .
@prefix foaf:  <http://xmlns.com/foaf/0.1/> .
@prefix dc:  <http://purl.org/dc/elements/1.1/> .
@prefix authz:  <http://fedora.info/definitions/v4/authorization#> .

<http://192.168.99.100:8080/fcrepo/rest/submissions/37/83/72/4e/3783724e-1abe-4f4f-953b-cecb17a35daa>
        rdf:type                      pass:Submission ;
        rdf:type                      fedora:Container ;
        rdf:type                      fedora:Resource ;
        fedora:lastModifiedBy         "admin"^^<http://www.w3.org/2001/XMLSchema#string> ;
        pass:aggregatedDepositStatus  "not-started"^^<http://www.w3.org/2001/XMLSchema#string> ;
        pass:user                     <http://192.168.99.100:8080/fcrepo/rest/users/1c/df/cd/03/1cdfcd03-0721-4215-9e5d-8ee331ba40b3> ;
        pass:grants                   <http://192.168.99.100:8080/fcrepo/rest/grants/17/7b/7f/44/177b7f44-b094-4ada-aef7-32528afc8dda> ;
        pass:submitted                "true"^^<http://www.w3.org/2001/XMLSchema#boolean> ;
        dcjsonld:hasContext           <https://oa-pass.github.io/pass-data-model/src/main/resources/context-2.0.jsonld> ;
        pass:submittedDate            "2018-05-17T19:19:08.770Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> ;
        fedora:createdBy              "admin"^^<http://www.w3.org/2001/XMLSchema#string> ;
        fedora:lastModified           "2018-05-17T19:19:09.542Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> ;
        fedora:created                "2018-05-17T19:19:09.542Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> ;
        pass:source                   "pass"^^<http://www.w3.org/2001/XMLSchema#string> ;
        pass:metadata                 "[{\"id\":\"JScholarship\",\"data\":{\"embargo\":\"NON-EXCLUSIVE LICENSE FOR USE OF MATERIALS This non-exclusive license defines the terms for the deposit of Materials in all formats into the digital repository of materials collected, preserved and made available through the Johns Hopkins Digital Repository, JScholarship. The Contributor hereby grants to Johns Hopkins a royalty free, non-exclusive worldwide license to use, re-use, display, distribute, transmit, publish, re-publish or copy the Materials, either digitally or in print, or in any other medium, now or hereafter known, for the purpose of including the Materials hereby licensed in the collection of materials in the Johns Hopkins Digital Repository for educational use worldwide. In some cases, access to content may be restricted according to provisions established in negotiation with the copyright holder. This license shall not authorize the commercial use of the Materials by Johns Hopkins or any other person or organization, but such Materials shall be restricted to non-profit educational use. Persons may apply for commercial use by contacting the copyright holder. Copyright and any other intellectual property right in or to the Materials shall not be transferred by this agreement and shall remain with the Contributor, or the Copyright holder if different from the Contributor. Other than this limited license, the Contributor or Copyright holder retains all rights, title, copyright and other interest in the images licensed. If the submission contains material for which the Contributor does not hold copyright, the Contributor represents that s/he has obtained the permission of the Copyright owner to grant Johns Hopkins the rights required by this license, and that such third-party owned material is clearly identified and acknowledged within the text or content of the submission. If the submission is based upon work that has been sponsored or supported by an agency or organization other than Johns Hopkins, the Contributor represents that s/he has fulfilled any right of review or other obligations required by such contract or agreement. Johns Hopkins will not make any alteration, other than as allowed by this license, to your submission. This agreement embodies the entire agreement of the parties. No modification of this agreement shall be of any effect unless it is made in writing and signed by all of the parties to the agreement.\",\"agreement-to-deposit\":\"true\"}},{\"id\":\"common\",\"data\":{\"title\":\"Correction to “Structure Based Design of Non-Natural Peptidic Macrocyclic Mcl-1 Inhibitors”\",\"container-title\":\"ACS Medicinal Chemistry Letters\",\"volume\":\"8\",\"issue\":\"11\",\"ISSN\":\"1948-5875,1948-5875\",\"URL\":\"http://dx.doi.org/10.1021/acsmedchemlett.7b00397\",\"authors\":[{\"author\":\"Jeffrey W. Johannes\",\"orcid\":\"http://orcid.org/0000-0001-7242-6682\"},{\"author\":\"Stephanie Bates\"},{\"author\":\"Carl Beigie\"},{\"author\":\"Matthew A. Belmonte\"},{\"author\":\"John Breen\"},{\"author\":\"Shenggen Cao\"},{\"author\":\"Paolo A. Centrella\"},{\"author\":\"Matthew A. Clark\"},{\"author\":\"John W. Cuozzo\"},{\"author\":\"Christoph E. Dumelin\"},{\"author\":\"Andrew D. Ferguson\",\"orcid\":\"http://orcid.org/0000-0002-1018-9631\"},{\"author\":\"Sevan Habeshian\"},{\"author\":\"David Hargreaves\"},{\"author\":\"Camil Joubran\"},{\"author\":\"Steven Kazmirski\"},{\"author\":\"Anthony D. Keefe\"},{\"author\":\"Michelle L. Lamb\",\"orcid\":\"http://orcid.org/0000-0002-3005-8065\"},{\"author\":\"Haiye Lan\"},{\"author\":\"Yunxia Li\"},{\"author\":\"Hao Ma\"},{\"author\":\"Scott Mlynarski\"},{\"author\":\"Martin J. Packer\"},{\"author\":\"Philip B. Rawlins\"},{\"author\":\"Daniel W. Robbins\"},{\"author\":\"Haidong Shen\"},{\"author\":\"Eric A. Sigel\"},{\"author\":\"Holly H. Soutter\"},{\"author\":\"Nancy Su\"},{\"author\":\"Dawn M. Troast\"},{\"author\":\"Haiyun Wang\"},{\"author\":\"Kate F. Wickson\"},{\"author\":\"Chengyan Wu\"},{\"author\":\"Ying Zhang\"},{\"author\":\"Qiuying Zhao\"},{\"author\":\"Xiaolan Zheng\"},{\"author\":\"Alexander W. Hird\"}]}},{\"id\":\"crossref\",\"data\":{\"doi\":\"10.1021/acsmedchemlett.7b00397\",\"publisher\":\"American Chemical Society (ACS)\",\"journal-title-short\":\"ACS Med. Chem. Lett.\"}}]"^^<http://www.w3.org/2001/XMLSchema#string> ;
        pass:publication              <http://192.168.99.100:8080/fcrepo/rest/publications/71/ff/e8/29/71ffe829-3fd1-42af-936a-30b4f9b1b2e5> ;
        pass:repositories             <http://192.168.99.100:8080/fcrepo/rest/repositories/43/dd/62/f2/43dd62f2-1487-4a79-b1a3-48bc12200a8f> ;
        rdf:type                      ldp:RDFSource ;
        rdf:type                      ldp:Container ;
        fedora:writable               "true"^^<http://www.w3.org/2001/XMLSchema#boolean> ;
        fedora:hasParent              <http://192.168.99.100:8080/fcrepo/rest/submissions> .

<http://192.168.99.100:8080/fcrepo/rest/files/5f/55/48/cd/5f5548cd-89fb-4e32-ab8b-f6d8c7a38ecc>
        pass:submission  <http://192.168.99.100:8080/fcrepo/rest/submissions/37/83/72/4e/3783724e-1abe-4f4f-953b-cecb17a35daa> .

<http://192.168.99.100:8080/fcrepo/rest/files/b5/25/20/2c/b525202c-b39d-4c7b-92bc-caa9f3c770e1>
        pass:submission  <http://192.168.99.100:8080/fcrepo/rest/submissions/37/83/72/4e/3783724e-1abe-4f4f-953b-cecb17a35daa> .
```

```
15:19:11.280 [aultMessageListenerContainer-2] DEBUG [SubmissionProcessor] - >>>> Unable to update status of http://192.168.99.100:8080/fcrepo/rest/submissions/37/83/72/4e/3783724e-1abe-4f4f-953b-cecb17a35daa to in-progress: Could not map JSON to Policy
java.lang.RuntimeException: Could not map JSON to Policy
	at org.dataconservancy.pass.client.adapter.PassJsonAdapterBasic.toModel(PassJsonAdapterBasic.java:102)
	at org.dataconservancy.pass.client.adapter.PassJsonAdapterBasic.toModel(PassJsonAdapterBasic.java:112)
	at org.dataconservancy.pass.client.fedora.FedoraPassCrudClient.readResource(FedoraPassCrudClient.java:182)
	at org.dataconservancy.pass.client.PassClientDefault.readResource(PassClientDefault.java:79)
	at org.dataconservancy.nihms.builder.fs.PassJsonFedoraAdapter.funderFcrepoToPass(PassJsonFedoraAdapter.java:248)
	at org.dataconservancy.nihms.builder.fs.PassJsonFedoraAdapter.fcrepoToPass(PassJsonFedoraAdapter.java:296)
	at org.dataconservancy.nihms.builder.fs.FcrepoModelBuilder.build(FcrepoModelBuilder.java:49)
	at org.dataconservancy.pass.deposit.messaging.service.SubmissionProcessor.lambda$accept$2(SubmissionProcessor.java:133)
	at org.dataconservancy.pass.deposit.messaging.support.CriticalPath.performCritical(CriticalPath.java:73)
	at org.dataconservancy.pass.deposit.messaging.service.SubmissionProcessor.accept(SubmissionProcessor.java:114)
	at org.dataconservancy.pass.deposit.messaging.service.JmsSubmissionProcessor.processInternal(JmsSubmissionProcessor.java:133)
	at org.dataconservancy.pass.deposit.messaging.service.JmsSubmissionProcessor.processMessage(JmsSubmissionProcessor.java:110)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:181)
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:114)
	at org.springframework.jms.listener.adapter.MessagingMessageListenerAdapter.invokeHandler(MessagingMessageListenerAdapter.java:114)
	at org.springframework.jms.listener.adapter.MessagingMessageListenerAdapter.onMessage(MessagingMessageListenerAdapter.java:77)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:736)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:696)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:674)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:318)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:257)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1189)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1179)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1076)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.net.URI` out of START_ARRAY token
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: org.dataconservancy.pass.model.Policy["funder"])
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1342)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1138)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer._deserializeFromArray(StdDeserializer.java:674)
	at com.fasterxml.jackson.databind.deser.std.FromStringDeserializer.deserialize(FromStringDeserializer.java:164)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:189)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:161)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:130)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:97)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeWithType(BeanDeserializerBase.java:1171)
	at com.fasterxml.jackson.databind.deser.impl.TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:68)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3972)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2264)
	at com.fasterxml.jackson.databind.ObjectMapper.treeToValue(ObjectMapper.java:2746)
	at org.dataconservancy.pass.client.adapter.PassJsonAdapterBasic.toModel(PassJsonAdapterBasic.java:99)
	... 28 common frames omitted
```

Below are the `Grant`, `Funder`, and `Policy`:
```
esm:~/workspaces/pass/nihms-submission/deposit-messaging (messaging)*$ curl -u admin:moo -H "Prefer: return=representation; include=\"http://fedora.info/definitions/v4/repository#InboundReferences\"" 'http://192.168.99.100:8080/fcrepo/rest/grants/17/7b/7f/44/177b7f44-b094-4ada-aef7-32528afc8dda'
@prefix premis:  <http://www.loc.gov/premis/rdf/v1#> .
@prefix test:  <info:fedora/test/> .
@prefix pass:  <http://example.org/pass/> .
@prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#> .
@prefix webac:  <http://fedora.info/definitions/v4/webac#> .
@prefix acl:  <http://www.w3.org/ns/auth/acl#> .
@prefix xsi:  <http://www.w3.org/2001/XMLSchema-instance> .
@prefix xmlns:  <http://www.w3.org/2000/xmlns/> .
@prefix rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix fedora:  <http://fedora.info/definitions/v4/repository#> .
@prefix xml:  <http://www.w3.org/XML/1998/namespace> .
@prefix dcjsonld:  <http://dataconservancy.org/ns/jsonld#> .
@prefix ebucore:  <http://www.ebu.ch/metadata/ontologies/ebucore/ebucore#> .
@prefix ldp:  <http://www.w3.org/ns/ldp#> .
@prefix xs:  <http://www.w3.org/2001/XMLSchema> .
@prefix fedoraconfig:  <http://fedora.info/definitions/v4/config#> .
@prefix foaf:  <http://xmlns.com/foaf/0.1/> .
@prefix dc:  <http://purl.org/dc/elements/1.1/> .
@prefix authz:  <http://fedora.info/definitions/v4/authorization#> .

<http://192.168.99.100:8080/fcrepo/rest/grants/17/7b/7f/44/177b7f44-b094-4ada-aef7-32528afc8dda>
        rdf:type               fedora:Container ;
        rdf:type               fedora:Resource ;
        rdf:type               pass:Grant ;
        fedora:lastModifiedBy  "admin"^^<http://www.w3.org/2001/XMLSchema#string> ;
        pass:directFunder      <http://192.168.99.100:8080/fcrepo/rest/funders/4c/ba/5e/34/4cba5e34-ad6b-4783-af1b-e0cfd6cf9435> ;
        pass:pi                <http://192.168.99.100:8080/fcrepo/rest/users/dc/4e/f2/09/dc4ef209-93ba-4a02-97b0-50da1480af89> ;
        dcjsonld:hasContext    <https://oa-pass.github.io/pass-data-model/src/main/resources/context-2.0.jsonld> ;
        fedora:createdBy       "admin"^^<http://www.w3.org/2001/XMLSchema#string> ;
        fedora:created         "2018-05-17T19:17:09.585Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> ;
        fedora:lastModified    "2018-05-17T19:17:48.309Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> ;
        pass:localKey          "16120629"^^<http://www.w3.org/2001/XMLSchema#string> ;
        pass:startDate         "2017-08-01T00:00:00.000Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> ;
        pass:primaryFunder     <http://192.168.99.100:8080/fcrepo/rest/funders/4c/ba/5e/34/4cba5e34-ad6b-4783-af1b-e0cfd6cf9435> ;
        pass:projectName       "Identification and Activation Mechanisms of Vagal and Spinal Nociceptors in Esophageal Mucosa"^^<http://www.w3.org/2001/XMLSchema#string> ;
        pass:awardStatus       "active"^^<http://www.w3.org/2001/XMLSchema#string> ;
        pass:awardNumber       "R01DK110366"^^<http://www.w3.org/2001/XMLSchema#string> ;
        pass:endDate           "2021-07-31T00:00:00.000Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> ;
        rdf:type               ldp:RDFSource ;
        rdf:type               ldp:Container ;
        fedora:writable        "true"^^<http://www.w3.org/2001/XMLSchema#boolean> ;
        fedora:hasParent       <http://192.168.99.100:8080/fcrepo/rest/grants> .

<http://192.168.99.100:8080/fcrepo/rest/submissions/37/83/72/4e/3783724e-1abe-4f4f-953b-cecb17a35daa>
        pass:grants  <http://192.168.99.100:8080/fcrepo/rest/grants/17/7b/7f/44/177b7f44-b094-4ada-aef7-32528afc8dda> .
esm:~/workspaces/pass/nihms-submission/deposit-messaging (messaging)*$ curl -u admin:moo -H "Prefer: return=representation; include=\"http://fedora.info/definitions/v4/repository#InboundReferences\"" 'http://192.168.99.100:8080/fcrepo/rest/funders/4c/ba/5e/34/4cba5e34-ad6b-4783-af1b-e0cfd6cf9435'
@prefix premis:  <http://www.loc.gov/premis/rdf/v1#> .
@prefix test:  <info:fedora/test/> .
@prefix pass:  <http://example.org/pass/> .
@prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#> .
@prefix webac:  <http://fedora.info/definitions/v4/webac#> .
@prefix acl:  <http://www.w3.org/ns/auth/acl#> .
@prefix xsi:  <http://www.w3.org/2001/XMLSchema-instance> .
@prefix xmlns:  <http://www.w3.org/2000/xmlns/> .
@prefix rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix fedora:  <http://fedora.info/definitions/v4/repository#> .
@prefix xml:  <http://www.w3.org/XML/1998/namespace> .
@prefix dcjsonld:  <http://dataconservancy.org/ns/jsonld#> .
@prefix ebucore:  <http://www.ebu.ch/metadata/ontologies/ebucore/ebucore#> .
@prefix ldp:  <http://www.w3.org/ns/ldp#> .
@prefix xs:  <http://www.w3.org/2001/XMLSchema> .
@prefix fedoraconfig:  <http://fedora.info/definitions/v4/config#> .
@prefix foaf:  <http://xmlns.com/foaf/0.1/> .
@prefix dc:  <http://purl.org/dc/elements/1.1/> .
@prefix authz:  <http://fedora.info/definitions/v4/authorization#> .

<http://192.168.99.100:8080/fcrepo/rest/funders/4c/ba/5e/34/4cba5e34-ad6b-4783-af1b-e0cfd6cf9435>
        rdf:type               fedora:Container ;
        rdf:type               fedora:Resource ;
        rdf:type               pass:Funder ;
        fedora:lastModifiedBy  "admin"^^<http://www.w3.org/2001/XMLSchema#string> ;
        pass:name              "National Institution of Diabetes and Digestion"^^<http://www.w3.org/2001/XMLSchema#string> ;
        dcjsonld:hasContext    <https://oa-pass.github.io/pass-data-model/src/main/resources/context-2.0.jsonld> ;
        pass:policy            <http://192.168.99.100:8080/fcrepo/rest/policies/38/cd/d1/c1/38cdd1c1-98fa-4096-95f7-906b82ca4d85> ;
        fedora:createdBy       "admin"^^<http://www.w3.org/2001/XMLSchema#string> ;
        fedora:created         "2018-05-17T19:17:07.725Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> ;
        pass:localKey          "niddk-nih"^^<http://www.w3.org/2001/XMLSchema#string> ;
        fedora:lastModified    "2018-05-17T19:17:43.102Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> ;
        pass:url               <https://www.niddk.nih.gov/> ;
        rdf:type               ldp:RDFSource ;
        rdf:type               ldp:Container ;
        fedora:writable        "true"^^<http://www.w3.org/2001/XMLSchema#boolean> ;
        fedora:hasParent       <http://192.168.99.100:8080/fcrepo/rest/funders> .

<http://192.168.99.100:8080/fcrepo/rest/grants/17/7b/7f/44/177b7f44-b094-4ada-aef7-32528afc8dda>
        pass:directFunder   <http://192.168.99.100:8080/fcrepo/rest/funders/4c/ba/5e/34/4cba5e34-ad6b-4783-af1b-e0cfd6cf9435> ;
        pass:primaryFunder  <http://192.168.99.100:8080/fcrepo/rest/funders/4c/ba/5e/34/4cba5e34-ad6b-4783-af1b-e0cfd6cf9435> .

<http://192.168.99.100:8080/fcrepo/rest/policies/38/cd/d1/c1/38cdd1c1-98fa-4096-95f7-906b82ca4d85>
        pass:funder  <http://192.168.99.100:8080/fcrepo/rest/funders/06/fd/80/b2/06fd80b2-996b-4d33-b9e3-d05c3e7b8f32> ;
        pass:funder  <http://192.168.99.100:8080/fcrepo/rest/funders/4c/ba/5e/34/4cba5e34-ad6b-4783-af1b-e0cfd6cf9435> ;
        pass:funder  <http://192.168.99.100:8080/fcrepo/rest/funders/61/f8/54/bc/61f854bc-a12d-4501-b066-25afce0d3683> ;
        pass:funder  <http://192.168.99.100:8080/fcrepo/rest/funders/d9/dc/7a/d9/d9dc7ad9-9941-4cd0-8ade-685964ddbd6e> .
esm:~/workspaces/pass/nihms-submission/deposit-messaging (messaging)*$ curl -u admin:moo -H "Prefer: return=representation; include=\"http://fedora.info/definitions/v4/repository#InboundReferences\"" 'http://192.168.99.100:8080/fcrepo/rest/policies/38/cd/d1/c1/38cdd1c1-98fa-4096-95f7-906b82ca4d85'
@prefix premis:  <http://www.loc.gov/premis/rdf/v1#> .
@prefix test:  <info:fedora/test/> .
@prefix pass:  <http://example.org/pass/> .
@prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#> .
@prefix webac:  <http://fedora.info/definitions/v4/webac#> .
@prefix acl:  <http://www.w3.org/ns/auth/acl#> .
@prefix xsi:  <http://www.w3.org/2001/XMLSchema-instance> .
@prefix xmlns:  <http://www.w3.org/2000/xmlns/> .
@prefix rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix fedora:  <http://fedora.info/definitions/v4/repository#> .
@prefix xml:  <http://www.w3.org/XML/1998/namespace> .
@prefix dcjsonld:  <http://dataconservancy.org/ns/jsonld#> .
@prefix ebucore:  <http://www.ebu.ch/metadata/ontologies/ebucore/ebucore#> .
@prefix ldp:  <http://www.w3.org/ns/ldp#> .
@prefix xs:  <http://www.w3.org/2001/XMLSchema> .
@prefix fedoraconfig:  <http://fedora.info/definitions/v4/config#> .
@prefix foaf:  <http://xmlns.com/foaf/0.1/> .
@prefix dc:  <http://purl.org/dc/elements/1.1/> .
@prefix authz:  <http://fedora.info/definitions/v4/authorization#> .

<http://192.168.99.100:8080/fcrepo/rest/policies/38/cd/d1/c1/38cdd1c1-98fa-4096-95f7-906b82ca4d85>
        rdf:type               fedora:Container ;
        rdf:type               fedora:Resource ;
        rdf:type               pass:Policy ;
        fedora:lastModifiedBy  "admin"^^<http://www.w3.org/2001/XMLSchema#string> ;
        pass:policyUrl         <https://publicaccess.nih.gov/policy.htm> ;
        dcjsonld:hasContext    <https://oa-pass.github.io/pass-data-model/src/main/resources/context-2.0.jsonld> ;
        pass:description       "The Director of the National Institutes of Health requires that all\n        investigators funded by the NIH submit or have submitted for them to the National\n        Library of Medicine's PubMed Central an electronic version of their final, peer-reviewed\n        manuscripts upon acceptance for publication, to be made publicly available no later\n        than 12 months after the official date of publication: Provided, that the NIH shall\n        implement the public access policy in a manner consistent with copyright law."^^<http://www.w3.org/2001/XMLSchema#string> ;
        fedora:createdBy       "admin"^^<http://www.w3.org/2001/XMLSchema#string> ;
        fedora:created         "2018-05-17T19:17:05.736Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> ;
        fedora:lastModified    "2018-05-17T19:17:41.415Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> ;
        pass:title             "National Institute of Health Public Access Policy"^^<http://www.w3.org/2001/XMLSchema#string> ;
        pass:funder            <http://192.168.99.100:8080/fcrepo/rest/funders/06/fd/80/b2/06fd80b2-996b-4d33-b9e3-d05c3e7b8f32> ;
        pass:funder            <http://192.168.99.100:8080/fcrepo/rest/funders/4c/ba/5e/34/4cba5e34-ad6b-4783-af1b-e0cfd6cf9435> ;
        pass:funder            <http://192.168.99.100:8080/fcrepo/rest/funders/61/f8/54/bc/61f854bc-a12d-4501-b066-25afce0d3683> ;
        pass:funder            <http://192.168.99.100:8080/fcrepo/rest/funders/d9/dc/7a/d9/d9dc7ad9-9941-4cd0-8ade-685964ddbd6e> ;
        pass:repositories      <http://192.168.99.100:8080/fcrepo/rest/repositories/76/79/78/4e/7679784e-5c47-4700-8f62-ce6c025ddf0e> ;
        rdf:type               ldp:RDFSource ;
        rdf:type               ldp:Container ;
        fedora:writable        "true"^^<http://www.w3.org/2001/XMLSchema#boolean> ;
        fedora:hasParent       <http://192.168.99.100:8080/fcrepo/rest/policies> .

<http://192.168.99.100:8080/fcrepo/rest/funders/61/f8/54/bc/61f854bc-a12d-4501-b066-25afce0d3683>
        pass:policy  <http://192.168.99.100:8080/fcrepo/rest/policies/38/cd/d1/c1/38cdd1c1-98fa-4096-95f7-906b82ca4d85> .

<http://192.168.99.100:8080/fcrepo/rest/funders/06/fd/80/b2/06fd80b2-996b-4d33-b9e3-d05c3e7b8f32>
        pass:policy  <http://192.168.99.100:8080/fcrepo/rest/policies/38/cd/d1/c1/38cdd1c1-98fa-4096-95f7-906b82ca4d85> .

<http://192.168.99.100:8080/fcrepo/rest/funders/d9/dc/7a/d9/d9dc7ad9-9941-4cd0-8ade-685964ddbd6e>
        pass:policy  <http://192.168.99.100:8080/fcrepo/rest/policies/38/cd/d1/c1/38cdd1c1-98fa-4096-95f7-906b82ca4d85> .

<http://192.168.99.100:8080/fcrepo/rest/funders/4c/ba/5e/34/4cba5e34-ad6b-4783-af1b-e0cfd6cf9435>
        pass:policy  <http://192.168.99.100:8080/fcrepo/rest/policies/38/cd/d1/c1/38cdd1c1-98fa-4096-95f7-906b82ca4d85> .
esm:~/workspaces/pass/nihms-submission/deposit-messaging (messaging)*$ 
```

**Comment by emetsger** [comment]
The json for the `Policy`:

```
esm:~/workspaces/pass/nihms-submission/deposit-messaging (messaging)*$ curl -u admin:moo -H "Accept: application/ld+json" 'http://192.168.99.100:8080/fcrepo/rest/policies/38/cd/d1/c1/38cdd1c1-98fa-4096-95f7-906b82ca4d85'
{
  "@id" : "http://192.168.99.100:8080/fcrepo/rest/policies/38/cd/d1/c1/38cdd1c1-98fa-4096-95f7-906b82ca4d85",
  "@type" : "Policy",
  "description" : "The Director of the National Institutes of Health requires that all\n        investigators funded by the NIH submit or have submitted for them to the National\n        Library of Medicine's PubMed Central an electronic version of their final, peer-reviewed\n        manuscripts upon acceptance for publication, to be made publicly available no later\n        than 12 months after the official date of publication: Provided, that the NIH shall\n        implement the public access policy in a manner consistent with copyright law.",
  "funder" : [ "http://192.168.99.100:8080/fcrepo/rest/funders/61/f8/54/bc/61f854bc-a12d-4501-b066-25afce0d3683", "http://192.168.99.100:8080/fcrepo/rest/funders/d9/dc/7a/d9/d9dc7ad9-9941-4cd0-8ade-685964ddbd6e", "http://192.168.99.100:8080/fcrepo/rest/funders/06/fd/80/b2/06fd80b2-996b-4d33-b9e3-d05c3e7b8f32", "http://192.168.99.100:8080/fcrepo/rest/funders/4c/ba/5e/34/4cba5e34-ad6b-4783-af1b-e0cfd6cf9435" ],
  "policyUrl" : "https://publicaccess.nih.gov/policy.htm",
  "repositories" : [ "http://192.168.99.100:8080/fcrepo/rest/repositories/76/79/78/4e/7679784e-5c47-4700-8f62-ce6c025ddf0e" ],
  "title" : "National Institute of Health Public Access Policy",
  "@context" : "https://oa-pass.github.io/pass-data-model/src/main/resources/context-2.0.jsonld"
}
```
