### ISSUE TITLE
Exception when performing submission using 0.0.1 tag in pass-docker

### ISSUE THREAD

**Issue by emetsger** [OA-PASS/nihms-submission#80]
6:59:56.557 [aultMessageListenerContainer-5] DEBUG [SubmissionProcessor] - >>>> Unable to update status of http://192.168.99.100:8080/fcrepo/rest/submissions/3e/b6/2d/a7/3eb62da7-3d1e-401e-bee8-d62ac5e001e0 to 'in-progress': null
java.lang.NullPointerException: null
	at org.dataconservancy.nihms.builder.fs.PassJsonFedoraAdapter.fcrepoToPass(PassJsonFedoraAdapter.java:386)
	at org.dataconservancy.nihms.builder.fs.FcrepoModelBuilder.build(FcrepoModelBuilder.java:49)
	at org.dataconservancy.pass.deposit.messaging.service.SubmissionProcessor.lambda$accept$30(SubmissionProcessor.java:134)
	at org.dataconservancy.pass.deposit.messaging.support.CriticalPath.performCritical(CriticalPath.java:151)
	at org.dataconservancy.pass.deposit.messaging.support.CriticalPath.performCritical(CriticalPath.java:86)
	at org.dataconservancy.pass.deposit.messaging.service.SubmissionProcessor.accept(SubmissionProcessor.java:115)
	at org.dataconservancy.pass.deposit.messaging.service.JmsSubmissionProcessor.processInternal(JmsSubmissionProcessor.java:127)
	at org.dataconservancy.pass.deposit.messaging.service.JmsSubmissionProcessor.processMessage(JmsSubmissionProcessor.java:104)
	at sun.reflect.GeneratedMethodAccessor23.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:181)
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:114)
	at org.springframework.jms.listener.adapter.MessagingMessageListenerAdapter.invokeHandler(MessagingMessageListenerAdapter.java:114)
	at org.springframework.jms.listener.adapter.MessagingMessageListenerAdapter.onMessage(MessagingMessageListenerAdapter.java:77)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:736)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:696)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:674)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:318)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:257)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1189)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1179)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1076)
	at java.lang.Thread.run(Thread.java:748)

**Comment by Trumbore** [comment]
Based on the line where this is happening, the call to get the incoming links to the Submission resource is returning null instead of a Collection of URIs.  Could this be because the Fedora server in this environment is not set up to allow querying for incoming links?  I can add a check for null if that is an acceptable return value from getting the incoming links.

**Comment by emetsger** [comment]
@Trumbore yeah this is a bit confusing.  The `PassClient.getIncoming(...)` method should never return `null`, nor should it ever return a `Map` with `null` keys or values.  And the `Collection` shouldn't have `null` entries either.  A mystery that a debugger would help with.

**Comment by emetsger** [comment]
@Trumbore Oh.  I see.  There's no key `submission` in the incoming links `Map`.  Gotcha.

**Comment by emetsger** [comment]
Resolved by being defensive when processing incoming links.
